<template>
    <section class="gold-ledger">
        <header><div><p class="eyebrow">账户 · 黄金详情</p><h1>{{ accountTitle || "把每一克记清楚" }}</h1></div><button :disabled="busy" @click="reload">刷新</button></header>
        <p class="notice">这里记录已经发生的买卖，不执行交易。账户余额按成本统计；没有有效报价时不显示市值。</p>
        <p v-if="error" role="alert" class="error">{{ error }}</p>
        <p v-if="message" role="status" class="notice">{{ message }}</p>
        <div v-if="!accountId" class="positions"><button v-for="p in positions" :key="p.id" :disabled="busy || !!pending" :class="{ selected: detail?.position.id === p.id }" @click="select(p.id)"><strong>{{ p.name }}</strong><span>{{ p.quantity }} 克</span><small>成本 ¥{{ investmentMoney(p.cost) }}</small></button></div>
        <details v-if="!pending && (!accountId || (accountTitle && !detail))" :open="!!accountId" class="panel"><summary>{{ accountId ? "为此账户启用克数记账" : "添加黄金持仓" }}</summary><p>先在“账户”中创建余额为零、没有流水的人民币投资账户，再在这里绑定。已有黄金通过“期初录入”登记，不会再次扣现金。</p>
            <form @submit.prevent="create"><label>持仓名称<input v-model="newName" maxlength="128" required :disabled="busy" /></label><label>专用成本账户<select v-model="newAccount" required :disabled="busy || !!accountId"><option value="">请选择</option><option v-for="a in costAccounts" :key="a.id" :value="a.id">{{ a.name }}</option></select></label><button :disabled="busy">创建持仓</button></form>
        </details>
        <template v-if="detail">
            <div class="metrics"><article><small>持有数量</small><strong>{{ detail.position.quantity }} 克</strong></article><article><small>剩余成本</small><strong>¥{{ investmentMoney(detail.position.cost) }}</strong></article><article><small>已实现盈亏</small><strong>¥{{ investmentMoney(detail.position.realized) }}</strong></article></div><p>平均成本约 ¥{{ investmentAverage(detail.position.cost, detail.position.quantity) }} / 克（含买入手续费）</p>
            <section class="panel"><h2>参考估值</h2><p v-if="!valuation">尚未读取行情，不影响记账。</p><template v-else-if="valuation.marketValue !== null"><p>参考市值 ¥{{ investmentMoney(valuation.marketValue) }} · 浮动盈亏 ¥{{ investmentMoney(valuation.unrealized || '0') }}</p><p>采集时间：{{ valuation.quote?.fetchedAt }} · MarketDay={{ valuation.quote?.marketDay }} · QuotedPrice={{ valuation.quote?.quotedPrice }}</p><p>按招行客户卖出参考价估算，最终成交以交易界面为准。银行原始 NowTime：{{ valuation.quote?.apiNowTime }}，不等于已确认的最后更新时间。</p></template><p v-else>{{ valuation.status === 'unconfigured' ? '行情通道尚未配置' : '行情暂不可用' }}，市值留空。</p><button :disabled="busy || !!pending" @click="readValuation">读取参考估值</button></section>
            <section class="panel"><h2>{{ form.operationId ? '更正已有记录' : '记录一笔' }}</h2>
                <form @submit.prevent="preview">
                    <fieldset :disabled="busy || !!pending"><div class="fields">
                        <label>操作<select v-model="form.kind"><option value="buy">买入</option><option value="sell">卖出</option><option value="opening">期初录入</option></select></label>
                        <label>实际发生时间<input v-model="date" type="datetime-local" step="1" required /></label>
                        <label>克数<input v-model="form.quantity" inputmode="decimal" required placeholder="例如 3.5" /></label>
                        <label>{{ form.kind === 'opening' ? '期初成本（元）' : '成交金额，不含另收手续费（元）' }}<input v-model="gross" inputmode="decimal" required /></label>
                        <label v-if="form.kind !== 'opening'">另收手续费（元）<input v-model="fee" inputmode="decimal" required /></label>
                        <template v-if="form.kind !== 'opening'"><label>付款 / 收款账户<select v-model="form.cashAccountId" required><option value="">请选择</option><option v-for="a in cashAccounts" :key="a.id" :value="a.id">{{ a.name }}</option></select></label>
                            <label>本金转账分类<select v-model="form.transferCategoryId" required><option value="">请选择</option><option v-for="a in categoriesOf(3)" :key="a.id" :value="a.id">{{ a.name }}</option></select></label>
                        </template>
                        <template v-if="form.kind === 'sell'"><label>投资收益分类<select v-model="form.incomeCategoryId" required><option value="">请选择</option><option v-for="a in categoriesOf(1)" :key="a.id" :value="a.id">{{ a.name }}</option></select></label><label>投资损失分类<select v-model="form.expenseCategoryId" required><option value="">请选择</option><option v-for="a in categoriesOf(2)" :key="a.id" :value="a.id">{{ a.name }}</option></select></label></template>
                        <label>备注<input v-model="form.comment" maxlength="255" /></label>
                    </div></fieldset>
                    <div class="actions"><button v-if="!pending" :disabled="busy" type="submit">检查入账结果</button><button v-if="form.operationId && !pending" :disabled="busy" type="button" @click="resetForm">取消更正</button></div>
                </form>
                <div v-if="pending && proposed" class="preview"><h3>请核对后保存</h3><p>{{ pending.cancelled ? '撤销这笔记录后' : '保存后' }}：{{ proposed.calculation.quantity }} 克，剩余成本 ¥{{ investmentMoney(proposed.calculation.cost) }}，累计已实现盈亏 ¥{{ investmentMoney(proposed.calculation.realized) }}。</p><p>补记或更正历史记录会同时重算受影响的后续成本与盈亏。</p><p>本次使现金合计变化 ¥{{ investmentMoney(previewCashDelta) }}；负数表示减少，正数表示增加。</p><div class="actions"><button :disabled="busy" @click="save">确认保存</button><button :disabled="busy" @click="cancelPreview">返回修改</button></div><p v-if="uncertain">尚未确认保存结果。请用“确认保存”重试同一请求，不要另建一笔。</p></div>
            </section>
            <section class="panel"><h2>买卖记录</h2><p v-if="!detail.operations.length">还没有记录。</p><article v-for="op in detail.operations" :key="op.operationId" class="operation"><div><strong>{{ labels[op.kind] }} · {{ op.quantity }} 克 <small v-if="op.cancelled">（已撤销）</small></strong><p>{{ new Date(op.occurredAt * 1000).toLocaleString() }} · ¥{{ investmentMoney(op.gross) }} · 手续费 ¥{{ investmentMoney(op.fee) }}</p><small>{{ op.comment }}</small><div class="actions"><button v-for="pic in (detail.attachments || []).filter(p => p.operationId === op.operationId)" :key="pic.pictureId" :disabled="busy" @click="viewPicture(pic.pictureId, pic.extension)">查看凭证</button></div></div><div v-if="!op.cancelled" class="actions"><label v-if="isTransactionPicturesEnabled()" class="receipt">添加凭证<input type="file" accept="image/png,image/jpeg,image/webp" :disabled="busy || !!pending" @change="attach($event, op.operationId)" /></label><button :disabled="busy || !!pending" @click="edit(op)">更正</button><button :disabled="busy || !!pending" @click="cancelOperation(op)">撤销</button></div></article></section>
            <details class="panel"><summary>更正与撤销历史</summary><p>历史版本保留，以下时间为实际记录时间。</p><article v-for="op in (detail.history || [])" :key="op.id" class="operation"><div><strong>{{ labels[op.kind] }} · 第 {{ op.revision }} 版 {{ op.cancelled ? '（撤销）' : '' }}</strong><p>{{ op.quantity }} 克 · 成交/期初 ¥{{ investmentMoney(op.gross) }} · 手续费 ¥{{ investmentMoney(op.fee) }}</p><small>{{ new Date(op.recordedAt * 1000).toLocaleString() }} · {{ op.comment }}</small></div></article></details>
        </template>
        <dialog ref="pictureDialog"><button @click="pictureDialog?.close()">关闭</button><img v-if="pictureURL" :src="pictureURL" alt="投资凭证" style="max-width:80vw;max-height:75vh" /></dialog>
    </section>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import services from '@/lib/services.ts';
import { isTransactionPicturesEnabled } from '@/lib/server_settings.ts';
import type { AccountInfoResponse } from '@/models/account.ts';
import type { TransactionCategoryInfoResponse } from '@/models/transaction_category.ts';
import { investmentMinorUnits, investmentMoney, investmentAverage, type InvestmentPosition, type InvestmentDetail, type InvestmentOperation, type InvestmentRequest } from '@/models/investment.ts';
const { accountId = '' } = defineProps<{ accountId?: string }>();
const accountTitle = ref('');
const pictureDialog = ref<HTMLDialogElement>(); const pictureURL = ref('');
const valuation = ref<Awaited<ReturnType<typeof services.getInvestmentValuation>>['data']['result']>();
const positions = ref<InvestmentPosition[]>([]), accounts = ref<AccountInfoResponse[]>([]), categories = ref<TransactionCategoryInfoResponse[]>([]);
const detail = ref<InvestmentDetail>(), proposed = ref<InvestmentDetail>(), pending = ref<InvestmentRequest>();
const busy = ref(false), error = ref(''), message = ref(''), uncertain = ref(false), newName = ref(''), newAccount = ref('');
let createAttempt: { requestKey: string; name: string; costAccountId: string } | undefined;
const labels = { opening: '期初', buy: '买入', sell: '卖出' };
const blank = (): InvestmentRequest => ({ requestKey: '', positionId: '', expectedVersion: 0, operationId: '', kind: 'buy', occurredAt: 0, utcOffset: 0, quantity: '', gross: '0', fee: '0', cashAccountId: '', transferCategoryId: '', incomeCategoryId: '', expenseCategoryId: '', cancelled: false, comment: '' });
const form = ref(blank()), gross = ref(''), fee = ref('0'), date = ref(localDate(Date.now()));
const previewCashDelta = computed(() => { const sum = (d?: InvestmentDetail): bigint => (d?.calculation.effects || []).reduce((v, e) => v + BigInt(e.cashDelta), 0n); return (sum(proposed.value) - sum(detail.value)).toString(); });
const costAccounts = computed(() => accounts.value.filter(a => a.category === 7 && a.balance === 0 && !positions.value.some(p => p.costAccountId === a.id)));
const cashAccounts = computed(() => accounts.value.filter(a => !positions.value.some(p => p.costAccountId === a.id)));
function localDate(time: number): string { const d = new Date(time); return new Date(time - d.getTimezoneOffset() * 60000).toISOString().slice(0, 19); }
function categoriesOf(type: number): TransactionCategoryInfoResponse[] { return categories.value.filter(c => c.type === type); }
function describe(e: unknown): string { const err = e as { response?: { data?: { errorMessage?: string } }; message?: string }; return err.response?.data?.errorMessage || err.message || '操作失败，请检查网络并重试。'; }
async function run(fn: () => Promise<void>): Promise<void> { if (busy.value) return; busy.value = true; error.value = ''; message.value = ''; try { await fn(); } catch (e) { error.value = describe(e); } finally { busy.value = false; } }
async function fetchPositions(): Promise<void> { positions.value = (await services.getInvestments()).data.result; }
async function reload(): Promise<void> { if (pending.value) { error.value = '请先完成或取消当前确认。'; return; } await run(async () => { await fetchPositions(); if (detail.value) detail.value = (await services.getInvestment(detail.value.position.id)).data.result; }); }
async function select(id: string): Promise<void> { if (pending.value) return; await run(async () => { detail.value = (await services.getInvestment(id)).data.result; resetForm(); }); }
function resetForm(): void { form.value = blank(); gross.value = ''; fee.value = '0'; date.value = localDate(Date.now()); pending.value = undefined; proposed.value = undefined; uncertain.value = false; }
async function create(): Promise<void> { await run(async () => { if (!createAttempt || createAttempt.name !== newName.value || createAttempt.costAccountId !== newAccount.value) createAttempt = { requestKey: crypto.randomUUID(), name: newName.value, costAccountId: newAccount.value }; const p = (await services.createInvestment(createAttempt)).data.result; createAttempt = undefined; await fetchPositions(); detail.value = (await services.getInvestment(p.id)).data.result; newName.value = ''; newAccount.value = ''; resetForm(); }); }
function request(): InvestmentRequest { if (!detail.value) throw new Error('请选择持仓'); const d = new Date(date.value); if (!Number.isFinite(d.getTime())) throw new Error('请选择有效时间'); return { ...form.value, requestKey: crypto.randomUUID(), positionId: detail.value.position.id, expectedVersion: detail.value.position.version, occurredAt: Math.floor(d.getTime() / 1000), utcOffset: -d.getTimezoneOffset(), gross: investmentMinorUnits(gross.value), fee: form.value.kind === 'opening' ? '0' : investmentMinorUnits(fee.value), cashAccountId: form.value.kind === 'opening' ? '0' : form.value.cashAccountId, transferCategoryId: form.value.transferCategoryId || '0', incomeCategoryId: form.value.incomeCategoryId || '0', expenseCategoryId: form.value.expenseCategoryId || '0' }; }
async function preview(): Promise<void> { await run(async () => { const req = request(); proposed.value = (await services.previewInvestment(req)).data.result; pending.value = req; }); }
async function save(): Promise<void> { if (!pending.value) return; await run(async () => { uncertain.value = true; try { detail.value = (await services.saveInvestment(pending.value!)).data.result; } catch (e) { const status = (e as { response?: { status?: number } }).response?.status; if (status && status >= 400 && status < 500 && status !== 408 && status !== 429) uncertain.value = false; throw e; } resetForm(); message.value = '已保存到账本。'; await fetchPositions(); }); }
function cancelPreview(): void { if (uncertain.value) { error.value = '结果尚不确定，请先重试原请求确认是否入库。'; return; } pending.value = undefined; proposed.value = undefined; }
function edit(op: InvestmentOperation): void { resetForm(); form.value = { ...blank(), ...op }; gross.value = investmentMoney(op.gross); fee.value = investmentMoney(op.fee); date.value = localDate(op.occurredAt * 1000); }
async function cancelOperation(op: InvestmentOperation): Promise<void> { edit(op); await run(async () => { const req = { ...request(), cancelled: true }; proposed.value = (await services.previewInvestment(req)).data.result; pending.value = req; }); }
watch(() => [detail.value?.position.id, detail.value?.position.version], () => { valuation.value = undefined; });
async function readValuation(): Promise<void> { if (!detail.value) return; await run(async () => { const result = (await services.getInvestmentValuation(detail.value!.position.id)).data.result; if (result.positionVersion !== undefined && result.positionVersion !== detail.value!.position.version) throw new Error('持仓已变化，请刷新后重新读取行情'); valuation.value = result; }); }
async function attach(event: Event, operationId: string): Promise<void> { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file || !detail.value) return; await run(async () => { const picture = (await services.uploadTransactionPicture({ pictureFile: file, clientSessionId: crypto.randomUUID() })).data.result; await services.attachInvestmentPicture({ positionId: detail.value!.position.id, operationId, pictureId: picture.pictureId }); detail.value = (await services.getInvestment(detail.value!.position.id)).data.result; message.value = '凭证已保存。'; }); input.value = ''; }
async function viewPicture(id: string, extension: string): Promise<void> { await run(async () => { const data = (await services.readInvestmentPicture(id, extension)).data; if (pictureURL.value) URL.revokeObjectURL(pictureURL.value); pictureURL.value = URL.createObjectURL(data); pictureDialog.value?.showModal(); }); }
onUnmounted(() => { if (pictureURL.value) URL.revokeObjectURL(pictureURL.value); });
onMounted(() => { void run(async () => { const [a, c] = await Promise.all([services.getAllAccounts({ visibleOnly: false }), services.getAllTransactionCategories()]); accounts.value = a.data.result.flatMap(a => a.subAccounts?.length ? a.subAccounts : [a]).filter(a => !a.hidden && a.currency === 'CNY' && a.type === 1); categories.value = Object.values(c.data.result).flatMap(group => group.flatMap(c => c.subCategories || [])).filter(c => !c.hidden); await fetchPositions(); if (accountId) { const account = a.data.result.flatMap(a => a.subAccounts?.length ? a.subAccounts : [a]).find(a => a.id === accountId); if (!account) throw new Error('账户不存在或无权访问，请返回账户列表。'); const position = positions.value.find(p => p.costAccountId === accountId); if (position) { detail.value = (await services.getInvestment(position.id)).data.result; accountTitle.value = account.name; } else { if (!costAccounts.value.some(a => a.id === accountId)) throw new Error('此账户不能启用黄金克数记账，请使用空的人民币投资账户。'); accountTitle.value = account.name; newAccount.value = accountId; newName.value = account.name; } } else if (positions.value[0]) detail.value = (await services.getInvestment(positions.value[0].id)).data.result; }); });
</script>

<style scoped>
.gold-ledger{max-width:1050px;margin:auto;padding:24px;color:inherit}.gold-ledger header,.operation{display:flex;justify-content:space-between;gap:16px;align-items:center}.eyebrow{font-size:12px;letter-spacing:.12em;color:#987633}h1{font-size:28px;margin:8px 0}h2{font-size:20px}.notice{opacity:.75;line-height:1.7}.error{background:#ffe6e3;color:#9b261e;padding:14px;border-radius:10px}.panel{border:1px solid #8884;border-radius:16px;padding:20px;margin:20px 0}.positions,.metrics{display:flex;gap:12px;flex-wrap:wrap}.positions button{display:grid;text-align:left;gap:6px}.positions .selected{border-color:#987633;background:#98763318}.metrics article{flex:1;min-width:150px;padding:20px;background:#98763310;border-radius:12px}.metrics strong{display:block;font-size:24px;margin-top:8px}fieldset{border:0;padding:0}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}label{display:flex;flex-direction:column;gap:8px;font-size:14px;margin-bottom:12px}input,select{border:1px solid #8886;border-radius:8px;padding:12px;background:transparent;color:inherit;width:100%;box-sizing:border-box;font:inherit}button{width:auto;border:1px solid #8886;border-radius:9px;padding:10px 16px;color:inherit;background:transparent;cursor:pointer;font:inherit}button:disabled{opacity:.45;cursor:default}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.preview{padding:18px;margin-top:20px;background:#98763315;border-radius:12px}.operation{border-top:1px solid #8883;padding:16px 0}.operation p{font-size:13px;opacity:.7}summary{cursor:pointer;font-weight:bold}@media(max-width:600px){.gold-ledger{padding:16px}.gold-ledger header>div{flex:1;min-width:0}.gold-ledger header>button{flex:none}h1{font-size:24px}.fields{grid-template-columns:1fr}.operation{display:block}.metrics{display:grid;grid-template-columns:1fr}.metrics article{min-width:0;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px}.metrics strong{font-size:20px;margin:0;overflow-wrap:anywhere}}
</style>
